require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'InScanner' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-perspective-image-cropper', :path => '../node_modules/react-native-perspective-image-cropper'





  pod 'RNPdfScanner', :path => '../node_modules/react-native-document-scanner'

  pod 'RNImageToPdf', :path => '../node_modules/react-native-image-to-pdf'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'InScannerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'InScanner-tvOS' do
  # Pods for InScanner-tvOS

  target 'InScanner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
